require(pkpkg)
setwd("C:/Users/simonh/Documents/Software/R_testing/r4mfcl")
a <- list.files("C:/Users/simonh/Documents/Software/r4mfcl/trunk/R4MFCL.src/R4MFCL/R/",full.names=T,pattern="?R")
for (x in a) source(x)
rm(a)
eez2new <- read.csv("C:/Users/simonh/Documents/Software/r4mfcl/trunk/R4MFCL.src/R4MFCL/inst/EZNEW2.TXT")
save(eez2new,file="C:/Users/simonh/Documents/Software/r4mfcl/trunk/R4MFCL.src/R4MFCL/data/eez2new.RData")
flaglist <- read.csv("C:/Users/simonh/Documents/Software/r4mfcl/trunk/R4MFCL.src/R4MFCL/inst/flaglist.csv")
save(flaglist,file="C:/Users/simonh/Documents/Software/r4mfcl/trunk/R4MFCL.src/R4MFCL/data/flaglist.RData")
albfrq_ex <- read.frq("L:/alb/2012/assessment/Runs/a0.ref/alb.frq")
albtag_ex <- read.tag("L:/alb/2012/assessment/Runs/a0.ref/alb.tag")
albini_ex <- read.ini("L:/alb/2012/assessment/Runs/a0.ref/alb.ini")
albvar_ex <- read.var("L:/alb/2012/assessment/Runs/a0.ref/alb.var")
albpar_ex <- read.par("L:/alb/2012/assessment/Runs/a0.ref/08.par")
albrep_ex <- read.rep("L:/alb/2012/assessment/Runs/a0.ref/plot-08.par.rep")
albdoit_ex <- readLines("L:/alb/2012/assessment/Runs/a0.ref/doitall.alb")
alb_MFCL <- list(frq=albfrq_ex,tag=albtag_ex,ini=albini_ex,par=albpar_ex,rep=albrep_ex,var=albvar_ex,doit=albdoit_ex)
save(alb_MFCL,file="C:/Users/simonh/Documents/Software/r4mfcl/trunk/R4MFCL.src/R4MFCL/data/alb_MFCL.RData")
skjfrq_ex <- read.frq("L:/skj/2011/results/skj.frq")
skjtag_ex <- read.tag("L:/skj/2011/results/skj.tag")
skjini_ex <- read.ini("L:/skj/2011/results/skj.ini")
skjvar_ex <- read.var("L:/skj/2011/results/skj.var")
skjpar_ex <- read.par("L:/skj/2011/results/17.par")
skjrep_ex <- read.rep("L:/skj/2011/results/plot-17.par.rep")
skjdoit_ex <- readLines("L:/skj/2011/results/doitall.skj")
skj_MFCL <- list(frq=skjfrq_ex,tag=skjtag_ex,ini=skjini_ex,par=skjpar_ex,rep=skjrep_ex,var=skjvar_ex,doit=skjdoit_ex)
save(skj_MFCL,file="C:/Users/simonh/Documents/Software/r4mfcl/trunk/R4MFCL.src/R4MFCL/data/skj_MFCL.RData")
detach(package:pkpkg)
rm(albfrq_ex,albtag_ex,albini_ex,albpar_ex,albrep_ex,albvar_ex,albdoit_ex,skjfrq_ex,skjtag_ex,skjini_ex,
  skjpar_ex,skjrep_ex,skjvar_ex,skjdoit_ex,x,eez2new,alb_MFCL,skj_MFCL,flaglist)
ls()
